# Generated by Django 4.2.16 on 2024-10-04 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del presupuesto', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del presupuesto')),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total inicial del presupuesto', max_digits=10)),
                ('monto_actual', models.DecimalField(decimal_places=2, default=0, help_text='Monto actual disponible', max_digits=10)),
                ('fecha_creacion', models.DateField(auto_now_add=True, help_text='Fecha de creación del presupuesto')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del presupuesto')),
                ('fecha_fin', models.DateField(help_text='Fecha de finalización del presupuesto')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', help_text='Estado del presupuesto', max_length=50)),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del ingreso', max_digits=10)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del ingreso')),
                ('fecha', models.DateField(help_text='Fecha del ingreso')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='Presupuesto.presupuesto')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del gasto', max_digits=10)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del gasto')),
                ('fecha', models.DateField(help_text='Fecha del gasto')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='Presupuesto.presupuesto')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
    ]
