# Generated by Django 4.2.16 on 2024-09-19 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Claseficacion_Partidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clasificacion', models.CharField(max_length=20, unique=True)),
                ('Descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clasificacion de Partidas',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Documento', models.CharField(max_length=20, unique=True)),
                ('Descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Documento', models.CharField(max_length=20, unique=True)),
                ('Descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfill_Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Empresa', models.CharField(max_length=20, unique=True)),
                ('Nombre_Empresa', models.CharField(max_length=20, unique=True)),
                ('Nombre_Comercial', models.CharField(max_length=20, unique=True)),
                ('Numero_NIT', models.CharField(max_length=20, unique=True)),
                ('Registro_Fiscal', models.CharField(max_length=20, unique=True)),
                ('Giro', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Perfil Empresa',
            },
        ),
        migrations.CreateModel(
            name='Departamentosv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_distrito', models.CharField(max_length=10, unique=True)),
                ('departamento_distrito', models.CharField(max_length=100)),
                ('encargado', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='Contabilidad.perfill_empresa')),
            ],
            options={
                'verbose_name_plural': 'Departamentos / Distritos',
            },
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COD_EMPRE', models.CharField(max_length=10)),
                ('NUMERO_CUENTA', models.CharField(max_length=20)),
                ('DESC_CUENTA', models.CharField(max_length=255)),
                ('NIVEL_CUENTA', models.IntegerField()),
                ('TIPO_CUENTA', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('costo', 'Costo')], max_length=50)),
                ('SUMA_DETALLE', models.CharField(choices=[('suma', 'Suma'), ('detalle', 'Detalle')], max_length=50)),
                ('TIPO_SALDO', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=50)),
                ('CLASIF_RESUL', models.CharField(choices=[('resultado', 'Resultado'), ('balance', 'Balance')], max_length=50)),
                ('AGRUPADOR_FLUJOE', models.CharField(blank=True, max_length=100, null=True)),
                ('MANUAL_CUENTA', models.BooleanField(default=False)),
                ('AGRUPADOR_FINANCIERO', models.CharField(blank=True, max_length=100, null=True)),
                ('CUENTA_INACTIVA', models.BooleanField(default=False)),
                ('DESC_CUENTA2', models.CharField(blank=True, max_length=255, null=True)),
                ('MOSTRAR_CONSULTA', models.BooleanField(default=True)),
                ('CENTRO_COSTO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Contabilidad.centrodecosto')),
                ('CUEN_DEPE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='Contabilidad.catalogo')),
            ],
            options={
                'verbose_name_plural': 'Catálogos',
            },
        ),
    ]
