# Generated by Django 4.2.16 on 2024-09-19 22:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0001_initial'),
    ]

    operations = [
        
        
    ]
