# Generated by Django 4.2.16 on 2024-09-19 22:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0002_partida_detallepartida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_partida', models.IntegerField(editable=False, null=True, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField()),
                ('valor_movimiento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Contabilidad.centrodecosto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contabilidad.perfill_empresa')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contabilidad.documento')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('abono', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cargo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contabilidad.catalogo')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Contabilidad.partida')),
            ],
        ),
    ]
