# Generated by Django 4.2.16 on 2024-09-19 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0003_partida_detallepartida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='centro_costo',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='tipo_documento',
        ),
    ]
