# Generated by Django 4.2.16 on 2024-09-19 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0004_remove_partida_centro_costo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 9, 19, 23, 1, 7, 396845, tzinfo=datetime.timezone.utc)),
        ),
    ]
