# Generated by Django 4.2.16 on 2024-10-04 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0005_alter_partida_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
