# Generated by Django 3.2.25 on 2024-09-16 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
