# Generated by Django 3.2.25 on 2024-09-16 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_factura_fecha_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoProyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('id_estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='register.estatu')),
                ('id_fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='register.fase')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='register.proyecto')),
            ],
        ),
    ]
