# Generated by Django 3.2.25 on 2024-09-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_fase_seguimientoproyectos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COD_EMPRE', models.CharField(max_length=100)),
                ('NUMERO_CUENTA', models.CharField(max_length=100)),
                ('DESC_CUENTA', models.CharField(max_length=255)),
                ('NIVEL_CUENTA', models.IntegerField()),
                ('TIPO_CUENTA', models.CharField(max_length=50)),
                ('SUMA_DETALLE', models.CharField(max_length=50)),
                ('CUEN_DEPE', models.CharField(max_length=50)),
                ('TIPO_SALDO', models.CharField(max_length=50)),
                ('CLASIF_RESUL', models.CharField(max_length=50)),
                ('CENTRO_COSTO', models.CharField(max_length=50)),
                ('AGRUPADOR_FLUJOE', models.CharField(max_length=50)),
                ('MANUAL_CUENTA', models.CharField(max_length=50)),
                ('AGRUPADOR_FINANCIERO', models.CharField(max_length=50)),
                ('CUENTA_INACTIVA', models.BooleanField(default=False)),
                ('DESC_CUENTA2', models.CharField(max_length=255)),
                ('MOSTRAR_CONSULTA', models.BooleanField(default=True)),
            ],
        ),
    ]
