# Generated by Django 3.2.25 on 2024-09-16 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_catalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='CUEN_DEPE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_cuentas', to='register.catalogo'),
        ),
    ]
