# Generated by Django 3.2.25 on 2024-09-16 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_catalogo_cuen_depe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo',
            options={'verbose_name_plural': 'Catálogos'},
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='AGRUPADOR_FINANCIERO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='AGRUPADOR_FLUJOE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='CENTRO_COSTO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='CLASIF_RESUL',
            field=models.CharField(choices=[('resultado', 'Resultado'), ('balance', 'Balance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='COD_EMPRE',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='CUEN_DEPE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='register.catalogo'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='DESC_CUENTA2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='MANUAL_CUENTA',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='NUMERO_CUENTA',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='SUMA_DETALLE',
            field=models.CharField(choices=[('suma', 'Suma'), ('detalle', 'Detalle')], max_length=50),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='TIPO_CUENTA',
            field=models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('costo', 'Costo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='TIPO_SALDO',
            field=models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=50),
        ),
    ]
