# Generated by Django 3.2.25 on 2024-09-16 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_centrodecosto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='CENTRO_COSTO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.centrodecosto'),
        ),
    ]
