# Generated by Django 4.2.16 on 2024-09-18 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_alter_catalogo_centro_costo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalogo',
        ),
        migrations.DeleteModel(
            name='CentroDeCosto',
        ),
    ]
