# Generated by Django 4.2.20 on 2025-04-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clientemt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('N', 'Persona Natural'), ('J', 'Persona Jurídica'), ('J', 'Persona Jurídica')], max_length=1)),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, null=True)),
                ('actividad_economica', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefonos', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nit', models.CharField(blank=True, max_length=20, null=True)),
                ('dui', models.CharField(blank=True, max_length=10, null=True)),
                ('nrc', models.CharField(blank=True, max_length=20, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
