# Generated by Django 4.2.20 on 2025-04-08 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroCliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemt',
            name='actividad_economica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RegistroCliente.actividadeconomica'),
        ),
    ]
