# Generated by Django 4.2.20 on 2025-04-08 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroCliente', '0002_alter_clientemt_actividad_economica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadeconomica',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientemt',
            name='actividad_economica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RegistroCliente.actividadeconomica'),
        ),
        migrations.AlterField(
            model_name='clientemt',
            name='direccion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='clientemt',
            name='documento',
            field=models.FileField(null=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='clientemt',
            name='dui',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientemt',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientemt',
            name='nit',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientemt',
            name='nombre_comercial',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientemt',
            name='nrc',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientemt',
            name='razon_social',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientemt',
            name='telefonos',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
