# Generated by Django 4.2.20 on 2025-04-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroCliente', '0003_alter_actividadeconomica_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientemt',
            name='documento',
        ),
        migrations.AddField(
            model_name='clientemt',
            name='dui_documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos/dui/'),
        ),
        migrations.AddField(
            model_name='clientemt',
            name='tarjeta_iva',
            field=models.FileField(blank=True, null=True, upload_to='documentos/tarjeta_iva/'),
        ),
        migrations.AddField(
            model_name='clientemt',
            name='tarjeta_nit',
            field=models.FileField(blank=True, null=True, upload_to='documentos/tarjeta_nit/'),
        ),
    ]
