# Generated by Django 4.2.20 on 2025-04-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroCliente', '0004_remove_clientemt_documento_clientemt_dui_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemt',
            name='categoria_contribuyente',
            field=models.CharField(choices=[('P', 'Pequeño'), ('M', 'Mediano'), ('G', 'Grande'), ('O', 'Otro')], max_length=1, null=True),
        ),
    ]
