# Generated by Django 4.2.20 on 2025-04-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroCliente', '0005_clientemt_categoria_contribuyente'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemt',
            name='correo_receptor_factura',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientemt',
            name='nombre_receptor_factura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientemt',
            name='telefono_receptor_factura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientemt',
            name='tipo_persona',
            field=models.CharField(choices=[('N', 'Persona Natural'), ('J', 'Persona Jurídica')], max_length=1),
        ),
    ]
