# Generated by Django 4.2.20 on 2025-04-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroCliente', '0006_clientemt_correo_receptor_factura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistritoMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_distrito', models.CharField(max_length=10, unique=True)),
                ('distrito', models.CharField(max_length=100)),
                ('codigo_municipio', models.CharField(max_length=10)),
                ('municipio', models.CharField(max_length=100)),
            ],
        ),
    ]
