# Generated by Django 4.2.20 on 2025-04-09 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroCliente', '0007_distritomunicipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemt',
            name='distritos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RegistroCliente.distritomunicipio'),
        ),
    ]
