# Generated by Django 4.2.20 on 2025-04-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroCliente', '0008_clientemt_distritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemt',
            name='categoria_contribuyente',
            field=models.CharField(choices=[('P', 'Pequeño'), ('M', 'Mediano'), ('G', 'Grande'), ('N', 'No aplica')], max_length=1, null=True),
        ),
    ]
